package rpc

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/magefile/mage/sh"
	"github.com/ttab/mage/internal"
	"go.yaml.in/yaml/v3"
)

// bufConfigName is the buf workspace configuration. It is only written when
// the workspace has more than one module root, which is what a vendored
// proto root makes it.
const bufConfigName = "buf.yaml"

// bufConfigMarker identifies a buf.yaml this package wrote. A file without
// it is somebody's own, and is left alone.
const bufConfigMarker = "# Generated by github.com/ttab/mage/rpc."

// bufTemplate is buf's generation configuration, passed to "buf generate"
// inline with --template so that no repository has to commit a buf.gen.yaml
// and every plugin version comes from this package.
type bufTemplate struct {
	Version string      `json:"version"`
	Plugins []bufPlugin `json:"plugins"`
}

type bufPlugin struct {
	Local []string `json:"local"`
	Out   string   `json:"out"`
	Opt   []string `json:"opt,omitempty"`
}

// generateCode runs the protobuf plugins over the discovered services.
//
// It is two buf runs rather than one, because the two service shapes get
// different plugin lists and buf takes one template per run. A shape with no
// services in it is not run at all. Everything the two runs have in common —
// the pins, the generator environment, the import path overrides and the
// output root — is worked out once.
func generateCode(conf config, services []service) error {
	err := ensureBufConfig(conf)
	if err != nil {
		return err
	}

	opts, err := pluginOptions(conf, services)
	if err != nil {
		return err
	}

	env, err := generatorEnv()
	if err != nil {
		return err
	}

	// The protoc-gen-twirp module is written here for the length of the
	// run. The plugins buf spawns take nothing from it but the command
	// line, so the directory only has to outlive buf.
	work, err := os.MkdirTemp("", "mage-rpc-")
	if err != nil {
		return fmt.Errorf("create the generator working directory: %w", err)
	}

	defer func() {
		_ = os.RemoveAll(work)
	}()

	var dualStack, native []service

	for _, s := range services {
		if s.Native {
			native = append(native, s)
		} else {
			dualStack = append(dualStack, s)
		}
	}

	if len(dualStack) > 0 {
		tpl, err := dualStackTemplate(conf, opts, work)
		if err != nil {
			return err
		}

		err = runGenerate(env, tpl, dualStack)
		if err != nil {
			return err
		}
	}

	if len(native) > 0 {
		err = runGenerate(env, nativeTemplate(conf, opts), native)
		if err != nil {
			return err
		}
	}

	return removeStaleInterfaces(conf, services)
}

// dualStackTemplate is the plugin list for a service that serves the plain
// protobuf interface: the messages, Connect, the adapters that put Connect on
// that interface, and Twirp while a repository still serves the /twirp/
// paths.
func dualStackTemplate(
	conf config, opts []string, work string,
) (bufTemplate, error) {
	tpl := nativeTemplate(conf, opts)

	elephantRPC, err := elephantRPCPlugin()
	if err != nil {
		return bufTemplate{}, err
	}

	tpl.Plugins = append(tpl.Plugins, bufPlugin{
		Local: elephantRPC,
		Out:   conf.ProtoRoot,
		Opt: append(append([]string{}, opts...),
			elephantRPCOptions(conf)...),
	})

	if conf.Twirp {
		twirp, err := twirpGenerator(work)
		if err != nil {
			return bufTemplate{}, err
		}

		tpl.Plugins = append(tpl.Plugins, bufPlugin{
			Local: twirp,
			Out:   conf.ProtoRoot,
			Opt:   opts,
		})
	}

	return tpl, nil
}

// nativeTemplate is the plugin list for a service that implements connect-go's
// own handler interface: the messages and Connect, and nothing of ours. It is
// also the first two plugins of the dual-stack list.
//
// The output root is the proto root rather than the repository root, because
// buf names a file relative to the module root and the module is rooted in the
// proto root. Source relative output then lands the generated code next to the
// declaration it came from, which is where it has always been.
func nativeTemplate(conf config, opts []string) bufTemplate {
	return bufTemplate{
		Version: "v2",
		Plugins: []bufPlugin{
			{
				Local: goRun(protocGenGoModule, ProtocGenGoVersion),
				Out:   conf.ProtoRoot,
				Opt:   opts,
			},
			{
				Local: goRun(connectGoModule, ConnectGoVersion),
				Out:   conf.ProtoRoot,
				Opt:   opts,
			},
		},
	}
}

// runGenerate runs one generation over the given services.
func runGenerate(
	env map[string]string, tpl bufTemplate, services []service,
) error {
	data, err := json.Marshal(tpl)
	if err != nil {
		return fmt.Errorf("marshal the buf template: %w", err)
	}

	args := append([]string{"generate", "--template", string(data)},
		pathArgs(services)...)

	err = buf(env, args...)
	if err != nil {
		return fmt.Errorf("run buf generate: %w", err)
	}

	return nil
}

// pathArgs scopes a buf run to the repository's own service declarations.
// Without them buf would take in every file in the workspace, vendored
// imports included: their Go code belongs to the module they were vendored
// out of, and so do the lint and breaking change rules they were written
// against.
func pathArgs(services []service) []string {
	var args []string

	for _, s := range services {
		args = append(args, "--path", s.Dir)
	}

	return args
}

// buf runs the pinned protobuf compiler.
func buf(env map[string]string, args ...string) error {
	full := append(goRun(bufModule, BufVersion), args...)

	err := sh.RunWithV(env, full[0], full[1:]...)
	if err != nil {
		return fmt.Errorf("run buf: %w", err)
	}

	return nil
}

// The generated files that declare the plain protobuf service interface.
// Exactly one of the two plugins writes it, and which one depends on whether
// the repository still generates Twirp, so turning that on or off leaves the
// other plugin's file behind — two declarations of the same interface in one
// package, which does not compile. elephant-public-api hit this and deleted
// the file by hand.
const (
	twirpSuffix        = ".twirp.go"
	rpcInterfaceSuffix = ".rpc.go"
	// elephantSuffix is the Connect adapters, which live in the connect
	// package one directory below the declaration.
	elephantSuffix = ".elephant.go"
)

// The header a plugin writes as the first line of its output. A file without
// it was written by hand, and generation deletes nobody's source.
const (
	twirpHeader       = "// Code generated by protoc-gen-twirp"
	elephantRPCHeader = "// Code generated by protoc-gen-elephant-rpc"
)

// staleFile is a generated file that has to go, and the header that says a
// generator wrote it.
type staleFile struct {
	// Dir is a glob for the directory to look in, since the adapters are
	// written into a connect package whose name comes from the
	// declaration.
	Dir    string
	Suffix string
	Header string
}

// removeStaleInterfaces deletes what a plugin that did not run this time
// wrote the last time it did.
//
// For a dual-stack service that is whichever of the two plain interface
// declarations is not being written. A native service is generated for by
// neither plugin, so both of them are stale for it, and so are the adapters:
// they take and return an interface that is no longer declared, so leaving
// them behind is a package that does not compile.
func removeStaleInterfaces(conf config, services []service) error {
	for _, s := range services {
		var stale []staleFile

		switch {
		case s.Native:
			stale = []staleFile{
				{Dir: s.Dir, Suffix: twirpSuffix, Header: twirpHeader},
				{Dir: s.Dir, Suffix: rpcInterfaceSuffix, Header: elephantRPCHeader},
				// The adapters are in "<declaration>/<package>connect".
				{
					Dir:    path.Join(s.Dir, "*"),
					Suffix: elephantSuffix,
					Header: elephantRPCHeader,
				},
			}
		default:
			if !conf.Twirp {
				stale = append(stale, staleFile{
					Dir: s.Dir, Suffix: twirpSuffix, Header: twirpHeader,
				})
			}

			if !interfaceEnabled(conf) {
				stale = append(stale, staleFile{
					Dir:    s.Dir,
					Suffix: rpcInterfaceSuffix,
					Header: elephantRPCHeader,
				})
			}
		}

		for _, f := range stale {
			err := removeGenerated(f.Dir, f.Suffix, f.Header)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

// removeGenerated deletes the files in a directory that end in a suffix and
// carry a generator's header. A file without the header is somebody's source,
// whatever it is called, and is left alone.
func removeGenerated(dir string, suffix string, header string) error {
	matches, err := filepath.Glob(filepath.Join(dir, "*"+suffix))
	if err != nil {
		return fmt.Errorf(
			"glob for stale %s files in %q: %w", suffix, dir, err)
	}

	for _, m := range matches {
		generated, err := hasHeader(m, header)
		if err != nil {
			return err
		}

		if !generated {
			continue
		}

		err = os.Remove(m)
		if err != nil {
			return fmt.Errorf("remove the stale %q: %w", m, err)
		}

		_, _ = fmt.Fprintf(os.Stdout,
			"removed %s, which is not generated any more\n", m)
	}

	return nil
}

// hasHeader reports whether a file starts with a generated code header.
func hasHeader(file string, header string) (bool, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return false, fmt.Errorf("read %q: %w", file, err)
	}

	return strings.HasPrefix(string(data), header), nil
}

// pluginOptions returns the options every plugin is given: source relative
// output, so that a file is generated next to the .proto it came from, and
// the Go import path of every proto file that does not declare a usable one
// itself.
func pluginOptions(conf config, services []service) ([]string, error) {
	opts := []string{"paths=source_relative"}

	mappings, err := goImportPathOverrides(conf, services)
	if err != nil {
		return nil, err
	}

	opts = append(opts, mappings...)

	return opts, nil
}

var goPackageExp = regexp.MustCompile(
	`(?m)^\s*option\s+go_package\s*=\s*"([^"]+)"`)

// goImportPathOverrides returns an M<file>=<import path> option per proto
// file that declares a relative go_package, or none at all, and checks the
// ones that do declare an import path.
//
// protoc-gen-go only takes the last element of go_package, as the name of
// the package it writes, so "./rpc/collab" has always worked. Connect
// generates into a subdirectory and has to import the message package, which
// a relative path cannot be turned into. Rather than making every repository
// edit its .proto files, the import path is derived here from the module
// path and the file's directory, which is where source relative output puts
// the generated code anyway.
//
// A declared import path has to be the same one, since that is where the
// generated code lands: a file whose go_package names anything else compiles
// into a package that imports itself under a name nothing provides, and the
// failure lands on whoever next builds the repository rather than on whoever
// wrote the declaration.
// An override is keyed on the name buf knows the file by, which is relative
// to the buf module root rather than to the repository root.
func goImportPathOverrides(conf config, services []service) ([]string, error) {
	module, err := modulePath()
	if err != nil {
		return nil, err
	}

	var opts []string

	for _, s := range services {
		files, err := protoFiles(s.Dir)
		if err != nil {
			return nil, err
		}

		wanted := module + "/" + s.Dir

		for _, f := range files {
			declared, err := declaredGoPackage(f)
			if err != nil {
				return nil, err
			}

			// A ";name" suffix names the Go package separately from
			// the import path, and is nobody's business here.
			path, _, _ := strings.Cut(declared, ";")

			if path == "" || strings.HasPrefix(path, ".") {
				opts = append(opts, fmt.Sprintf("M%s=%s",
					bufName(conf, f), wanted))

				continue
			}

			if path != wanted {
				return nil, fmt.Errorf(
					"%s declares go_package %q, but the generated"+
						" code is written next to it and has to be"+
						" importable as %q: correct the declaration,"+
						" or write it as a relative path and let it"+
						" be derived",
					filepath.ToSlash(f), path, wanted)
			}
		}
	}

	sort.Strings(opts)

	return opts, nil
}

func declaredGoPackage(file string) (string, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return "", fmt.Errorf("read %q: %w", file, err)
	}

	match := goPackageExp.FindSubmatch(data)
	if match == nil {
		return "", nil
	}

	return string(match[1]), nil
}

// bufName returns the name buf knows a file by. buf names a file relative to
// the root of the module it belongs to, and the module the repository's own
// declarations are in is rooted in the proto root, so a path from the
// repository root is not what a plugin option or a file descriptor says.
func bufName(conf config, file string) string {
	p := filepath.ToSlash(file)

	if conf.ProtoRoot == "." {
		return p
	}

	return strings.TrimPrefix(p, conf.ProtoRoot+"/")
}

func protoFiles(dir string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.proto"))
	if err != nil {
		return nil, fmt.Errorf("glob for proto files in %q: %w", dir, err)
	}

	return files, nil
}

func modulePath() (string, error) {
	path, err := internal.OutputSilent("go", "list", "-m", "-f", "{{.Path}}")
	if err != nil {
		return "", fmt.Errorf("resolve the Go module path: %w", err)
	}

	path = strings.TrimSpace(path)
	if path == "" {
		return "", fmt.Errorf(
			"the Go module path is empty, so the import path of the generated code cannot be derived")
	}

	return path, nil
}

// ensureBufConfig writes the buf workspace configuration, when the workspace
// needs one. A repository that keeps its protobuf sources in the repository
// root and vendors nothing needs none: a single module rooted where buf is
// run is what buf assumes with no configuration at all.
//
// Everything else needs one, for one of two reasons. A proto root under "rpc"
// has to be the module root, since that is what buf checks a package name and
// resolves an import against. A vendored proto root has to be a module of its
// own, since a vendored file keeps the path it had in the repository it came
// from.
func ensureBufConfig(conf config) error {
	roots, err := workspaceRoots(conf)
	if err != nil {
		return err
	}

	if conf.ProtoRoot == "." && len(roots) == 0 {
		return nil
	}

	wanted := bufConfig(conf.ProtoRoot, roots)

	current, err := os.ReadFile(bufConfigName)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", bufConfigName, err)
	}

	if len(current) > 0 && !strings.HasPrefix(string(current), bufConfigMarker) {
		// Somebody wrote their own workspace configuration. Buf lint and
		// breaking change rules live in the same file, so overwriting it
		// would throw those away. It still has to describe the roots:
		// the module root decides where the generated code lands and
		// what a package name is checked against, and a vendored root
		// that is not a module of its own leaves buf unable to find the
		// import it was vendored in for.
		return checkBufConfig(current, conf.ProtoRoot, roots)
	}

	if string(current) == wanted {
		return nil
	}

	err = os.WriteFile(bufConfigName, []byte(wanted), 0o600)
	if err != nil {
		return fmt.Errorf("write %s: %w", bufConfigName, err)
	}

	return nil
}

// workspaceRoots returns the proto roots beyond the repository root, or
// nothing when there are none.
func workspaceRoots(conf config) ([]string, error) {
	var roots []string

	vendored, err := internal.DirectoryExists(conf.VendorDir)
	if err != nil {
		return nil, fmt.Errorf("check for the vendored proto root: %w", err)
	}

	if vendored {
		roots = append(roots, conf.VendorDir)
	}

	for _, r := range conf.ExtraProtoRoots {
		roots = append(roots, filepath.ToSlash(r))
	}

	return roots, nil
}

// bufWorkspace is as much of buf.yaml as this package has an opinion about.
type bufWorkspace struct {
	Modules []struct {
		Path     string   `yaml:"path"`
		Excludes []string `yaml:"excludes"`
	} `yaml:"modules"`
}

// checkBufConfig reports what a hand-written buf.yaml is missing. Reporting
// it is all it does: lint and breaking change rules live in the same file, so
// the fix is somebody's editorial decision rather than a rewrite.
func checkBufConfig(data []byte, root string, roots []string) error {
	var workspace bufWorkspace

	err := yaml.Unmarshal(data, &workspace)
	if err != nil {
		return fmt.Errorf(
			"parse the hand-written %s: %w", bufConfigName, err)
	}

	var (
		declared = make(map[string]bool)
		excluded = make(map[string]bool)
	)

	for _, m := range workspace.Modules {
		p := path.Clean(m.Path)
		declared[p] = true

		if p != root {
			continue
		}

		for _, e := range m.Excludes {
			excluded[path.Clean(e)] = true
		}
	}

	var missing []string

	if !declared[root] {
		missing = append(missing, fmt.Sprintf(
			"the proto root %q is not the module root, and buf checks a"+
				" package name and resolves an import against the"+
				" module root: declare it as %q, rather than as any"+
				" directory above it",
			root, "  - path: "+root))
	}

	for _, r := range roots {
		if !declared[r] {
			missing = append(missing, fmt.Sprintf(
				"%q is not declared as a module: add %q under modules",
				r, "  - path: "+r))
		}

		if withinRoot(root, r) && !excluded[r] {
			missing = append(missing, fmt.Sprintf(
				"%q is not excluded from the module rooted in %q, so"+
					" buf sees every file in it twice: add %q to"+
					" that module's excludes",
				r, root, "      - "+r))
		}
	}

	if len(missing) == 0 {
		return nil
	}

	return fmt.Errorf(
		"the hand-written %s does not describe the proto roots this"+
			" repository generates from: %s",
		bufConfigName, strings.Join(missing, "; "))
}

// withinRoot reports whether a directory is inside a module root, and so has
// to be excluded from it to keep buf from reading its files twice.
func withinRoot(root string, dir string) bool {
	if root == "." {
		return true
	}

	return dir == root || strings.HasPrefix(dir, root+"/")
}

func bufConfig(root string, roots []string) string {
	var b strings.Builder

	b.WriteString(bufConfigMarker)
	b.WriteString(`
#
# The module root is the proto root. buf checks a file's package against the
# directory it is in relative to the module root, and resolves an import
# against the same root, so a declaration under a proto root is only itself
# from a module rooted there.
#
# A vendored protobuf file is imported by the path it has in the repository
# it came from, so its directory has to be a module root of its own, and be
# excluded from the module above when it is inside it.
version: v2
modules:
`)

	fmt.Fprintf(&b, "  - path: %s\n", root)

	var inside []string

	for _, r := range roots {
		if withinRoot(root, r) {
			inside = append(inside, r)
		}
	}

	if len(inside) > 0 {
		b.WriteString("    excludes:\n")

		for _, r := range inside {
			fmt.Fprintf(&b, "      - %s\n", r)
		}
	}

	for _, r := range roots {
		fmt.Fprintf(&b, "  - path: %s\n", r)
	}

	return b.String()
}
