package rpc

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/magefile/mage/sh"
	"github.com/ttab/mage/internal"
	"go.yaml.in/yaml/v3"
)

// bufConfigName is the buf workspace configuration. It is only written when
// the workspace has more than one module root, which is what a vendored
// proto root makes it.
const bufConfigName = "buf.yaml"

// bufConfigMarker identifies a buf.yaml this package wrote. A file without
// it is somebody's own, and is left alone.
const bufConfigMarker = "# Generated by github.com/ttab/mage/rpc."

// bufTemplate is buf's generation configuration, passed to "buf generate"
// inline with --template so that no repository has to commit a buf.gen.yaml
// and every plugin version comes from this package.
type bufTemplate struct {
	Version string      `json:"version"`
	Plugins []bufPlugin `json:"plugins"`
}

type bufPlugin struct {
	Local []string `json:"local"`
	Out   string   `json:"out"`
	Opt   []string `json:"opt,omitempty"`
}

// generateCode runs the protobuf plugins over the discovered services.
func generateCode(conf config, services []service) error {
	err := ensureBufConfig(conf)
	if err != nil {
		return err
	}

	opts, err := pluginOptions(services)
	if err != nil {
		return err
	}

	env, err := generatorEnv()
	if err != nil {
		return err
	}

	// The protoc-gen-twirp module is written here for the length of the
	// run. The plugins buf spawns take nothing from it but the command
	// line, so the directory only has to outlive buf.
	work, err := os.MkdirTemp("", "mage-rpc-")
	if err != nil {
		return fmt.Errorf("create the generator working directory: %w", err)
	}

	defer func() {
		_ = os.RemoveAll(work)
	}()

	tpl := bufTemplate{Version: "v2"}

	tpl.Plugins = append(tpl.Plugins,
		bufPlugin{
			Local: goRun(protocGenGoModule, ProtocGenGoVersion),
			Out:   ".",
			Opt:   opts,
		},
		bufPlugin{
			Local: goRun(connectGoModule, ConnectGoVersion),
			Out:   ".",
			Opt:   opts,
		})

	elephantRPC, err := elephantRPCPlugin()
	if err != nil {
		return err
	}

	tpl.Plugins = append(tpl.Plugins, bufPlugin{
		Local: elephantRPC,
		Out:   ".",
		Opt: append(append([]string{}, opts...),
			elephantRPCOptions(conf)...),
	})

	if conf.Twirp {
		twirp, err := twirpGenerator(work)
		if err != nil {
			return err
		}

		tpl.Plugins = append(tpl.Plugins, bufPlugin{
			Local: twirp,
			Out:   ".",
			Opt:   opts,
		})
	}

	data, err := json.Marshal(tpl)
	if err != nil {
		return fmt.Errorf("marshal the buf template: %w", err)
	}

	args := []string{"generate", "--template", string(data)}

	// Without --path buf would generate for every file in the workspace,
	// vendored imports included, and their Go code belongs to the module
	// they were vendored out of.
	for _, s := range services {
		args = append(args, "--path", s.Dir)
	}

	err = buf(env, args...)
	if err != nil {
		return fmt.Errorf("run buf generate: %w", err)
	}

	return removeStaleInterfaces(conf, services)
}

// buf runs the pinned protobuf compiler.
func buf(env map[string]string, args ...string) error {
	full := append(goRun(bufModule, BufVersion), args...)

	err := sh.RunWithV(env, full[0], full[1:]...)
	if err != nil {
		return fmt.Errorf("run buf: %w", err)
	}

	return nil
}

// The generated files that declare the plain protobuf service interface.
// Exactly one of the two plugins writes it, and which one depends on whether
// the repository still generates Twirp, so turning that on or off leaves the
// other plugin's file behind — two declarations of the same interface in one
// package, which does not compile. elephant-public-api hit this and deleted
// the file by hand.
const (
	twirpSuffix        = ".twirp.go"
	rpcInterfaceSuffix = ".rpc.go"
)

// The header a plugin writes as the first line of its output. A file without
// it was written by hand, and generation deletes nobody's source.
const (
	twirpHeader       = "// Code generated by protoc-gen-twirp"
	elephantRPCHeader = "// Code generated by protoc-gen-elephant-rpc"
)

// removeStaleInterfaces deletes what a plugin that did not run this time
// wrote the last time it did.
func removeStaleInterfaces(conf config, services []service) error {
	stale := map[string]string{}

	if !conf.Twirp {
		stale[twirpSuffix] = twirpHeader
	}

	if !interfaceEnabled(conf) {
		stale[rpcInterfaceSuffix] = elephantRPCHeader
	}

	for suffix, header := range stale {
		for _, s := range services {
			err := removeGenerated(s.Dir, suffix, header)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

// removeGenerated deletes the files in a directory that end in a suffix and
// carry a generator's header. A file without the header is somebody's source,
// whatever it is called, and is left alone.
func removeGenerated(dir string, suffix string, header string) error {
	matches, err := filepath.Glob(filepath.Join(dir, "*"+suffix))
	if err != nil {
		return fmt.Errorf(
			"glob for stale %s files in %q: %w", suffix, dir, err)
	}

	for _, m := range matches {
		generated, err := hasHeader(m, header)
		if err != nil {
			return err
		}

		if !generated {
			continue
		}

		err = os.Remove(m)
		if err != nil {
			return fmt.Errorf("remove the stale %q: %w", m, err)
		}

		_, _ = fmt.Fprintf(os.Stdout,
			"removed %s, which is not generated any more\n", m)
	}

	return nil
}

// hasHeader reports whether a file starts with a generated code header.
func hasHeader(file string, header string) (bool, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return false, fmt.Errorf("read %q: %w", file, err)
	}

	return strings.HasPrefix(string(data), header), nil
}

// pluginOptions returns the options every plugin is given: source relative
// output, so that a file is generated next to the .proto it came from, and
// the Go import path of every proto file that does not declare a usable one
// itself.
func pluginOptions(services []service) ([]string, error) {
	opts := []string{"paths=source_relative"}

	mappings, err := goImportPathOverrides(services)
	if err != nil {
		return nil, err
	}

	opts = append(opts, mappings...)

	return opts, nil
}

var goPackageExp = regexp.MustCompile(
	`(?m)^\s*option\s+go_package\s*=\s*"([^"]+)"`)

// goImportPathOverrides returns an M<file>=<import path> option per proto
// file that declares a relative go_package, or none at all, and checks the
// ones that do declare an import path.
//
// protoc-gen-go only takes the last element of go_package, as the name of
// the package it writes, so "./rpc/collab" has always worked. Connect
// generates into a subdirectory and has to import the message package, which
// a relative path cannot be turned into. Rather than making every repository
// edit its .proto files, the import path is derived here from the module
// path and the file's directory, which is where source relative output puts
// the generated code anyway.
//
// A declared import path has to be the same one, since that is where the
// generated code lands: a file whose go_package names anything else compiles
// into a package that imports itself under a name nothing provides, and the
// failure lands on whoever next builds the repository rather than on whoever
// wrote the declaration.
func goImportPathOverrides(services []service) ([]string, error) {
	module, err := modulePath()
	if err != nil {
		return nil, err
	}

	var opts []string

	for _, s := range services {
		files, err := protoFiles(s.Dir)
		if err != nil {
			return nil, err
		}

		wanted := module + "/" + s.Dir

		for _, f := range files {
			declared, err := declaredGoPackage(f)
			if err != nil {
				return nil, err
			}

			// A ";name" suffix names the Go package separately from
			// the import path, and is nobody's business here.
			path, _, _ := strings.Cut(declared, ";")

			if path == "" || strings.HasPrefix(path, ".") {
				opts = append(opts, fmt.Sprintf("M%s=%s",
					filepath.ToSlash(f), wanted))

				continue
			}

			if path != wanted {
				return nil, fmt.Errorf(
					"%s declares go_package %q, but the generated"+
						" code is written next to it and has to be"+
						" importable as %q: correct the declaration,"+
						" or write it as a relative path and let it"+
						" be derived",
					filepath.ToSlash(f), path, wanted)
			}
		}
	}

	sort.Strings(opts)

	return opts, nil
}

func declaredGoPackage(file string) (string, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return "", fmt.Errorf("read %q: %w", file, err)
	}

	match := goPackageExp.FindSubmatch(data)
	if match == nil {
		return "", nil
	}

	return string(match[1]), nil
}

func protoFiles(dir string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.proto"))
	if err != nil {
		return nil, fmt.Errorf("glob for proto files in %q: %w", dir, err)
	}

	return files, nil
}

func modulePath() (string, error) {
	path, err := internal.OutputSilent("go", "list", "-m", "-f", "{{.Path}}")
	if err != nil {
		return "", fmt.Errorf("resolve the Go module path: %w", err)
	}

	path = strings.TrimSpace(path)
	if path == "" {
		return "", fmt.Errorf(
			"the Go module path is empty, so the import path of the generated code cannot be derived")
	}

	return path, nil
}

// ensureBufConfig writes the buf workspace configuration, when the workspace
// needs one. A single module rooted in the repository is what buf assumes
// with no configuration at all, and that is the common case.
func ensureBufConfig(conf config) error {
	roots, err := workspaceRoots(conf)
	if err != nil {
		return err
	}

	if len(roots) == 0 {
		return nil
	}

	wanted := bufConfig(roots)

	current, err := os.ReadFile(bufConfigName)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", bufConfigName, err)
	}

	if len(current) > 0 && !strings.HasPrefix(string(current), bufConfigMarker) {
		// Somebody wrote their own workspace configuration. Buf lint and
		// breaking change rules live in the same file, so overwriting it
		// would throw those away. It still has to declare the roots: the
		// only reason the repository needs a workspace at all is that a
		// proto root outside the repository root has to resolve, and one
		// that is missing here leaves buf unable to find the import.
		return checkBufConfig(current, roots)
	}

	if string(current) == wanted {
		return nil
	}

	err = os.WriteFile(bufConfigName, []byte(wanted), 0o600)
	if err != nil {
		return fmt.Errorf("write %s: %w", bufConfigName, err)
	}

	return nil
}

// workspaceRoots returns the proto roots beyond the repository root, or
// nothing when there are none.
func workspaceRoots(conf config) ([]string, error) {
	var roots []string

	vendored, err := internal.DirectoryExists(conf.VendorDir)
	if err != nil {
		return nil, fmt.Errorf("check for the vendored proto root: %w", err)
	}

	if vendored {
		roots = append(roots, conf.VendorDir)
	}

	for _, r := range conf.ExtraProtoRoots {
		roots = append(roots, filepath.ToSlash(r))
	}

	return roots, nil
}

// bufWorkspace is as much of buf.yaml as this package has an opinion about.
type bufWorkspace struct {
	Modules []struct {
		Path     string   `yaml:"path"`
		Excludes []string `yaml:"excludes"`
	} `yaml:"modules"`
}

// checkBufConfig reports what a hand-written buf.yaml is missing. Reporting
// it is all it does: lint and breaking change rules live in the same file, so
// the fix is somebody's editorial decision rather than a rewrite.
func checkBufConfig(data []byte, roots []string) error {
	var workspace bufWorkspace

	err := yaml.Unmarshal(data, &workspace)
	if err != nil {
		return fmt.Errorf(
			"parse the hand-written %s: %w", bufConfigName, err)
	}

	var (
		declared = make(map[string]bool)
		excluded = make(map[string]bool)
	)

	for _, m := range workspace.Modules {
		p := path.Clean(m.Path)
		declared[p] = true

		if p != "." {
			continue
		}

		for _, e := range m.Excludes {
			excluded[path.Clean(e)] = true
		}
	}

	var missing []string

	for _, r := range roots {
		if !declared[r] {
			missing = append(missing, fmt.Sprintf(
				"%q is not declared as a module: add %q under modules",
				r, "  - path: "+r))
		}

		if !excluded[r] {
			missing = append(missing, fmt.Sprintf(
				"%q is not excluded from the module rooted in the"+
					" repository, so buf sees every file in it"+
					" twice: add %q to that module's excludes",
				r, "      - "+r))
		}
	}

	if len(missing) == 0 {
		return nil
	}

	return fmt.Errorf(
		"the hand-written %s does not describe the proto roots this"+
			" repository generates from: %s",
		bufConfigName, strings.Join(missing, "; "))
}

func bufConfig(roots []string) string {
	var b strings.Builder

	b.WriteString(bufConfigMarker)
	b.WriteString(`
#
# A vendored protobuf file is imported by the path it has in the repository
# it came from, so its directory has to be a module root of its own, and be
# excluded from the module rooted here.
version: v2
modules:
  - path: .
    excludes:
`)

	for _, r := range roots {
		fmt.Fprintf(&b, "      - %s\n", r)
	}

	for _, r := range roots {
		fmt.Fprintf(&b, "  - path: %s\n", r)
	}

	return b.String()
}
