package rpc

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/magefile/mage/sh"
	"github.com/ttab/mage/internal"
)

// bufConfigName is the buf workspace configuration. It is only written when
// the workspace has more than one module root, which is what a vendored
// proto root makes it.
const bufConfigName = "buf.yaml"

// bufConfigMarker identifies a buf.yaml this package wrote. A file without
// it is somebody's own, and is left alone.
const bufConfigMarker = "# Generated by github.com/ttab/mage/rpc."

// bufTemplate is buf's generation configuration, passed to "buf generate"
// inline with --template so that no repository has to commit a buf.gen.yaml
// and every plugin version comes from this package.
type bufTemplate struct {
	Version string      `json:"version"`
	Plugins []bufPlugin `json:"plugins"`
}

type bufPlugin struct {
	Local []string `json:"local"`
	Out   string   `json:"out"`
	Opt   []string `json:"opt,omitempty"`
}

// generateCode runs the protobuf plugins over the discovered services.
func generateCode(conf config, services []service) error {
	err := ensureBufConfig(conf)
	if err != nil {
		return err
	}

	opts, err := pluginOptions(services)
	if err != nil {
		return err
	}

	tpl := bufTemplate{Version: "v2"}

	tpl.Plugins = append(tpl.Plugins,
		bufPlugin{
			Local: goRun(protocGenGoModule, ProtocGenGoVersion),
			Out:   ".",
			Opt:   opts,
		},
		bufPlugin{
			Local: goRun(connectGoModule, ConnectGoVersion),
			Out:   ".",
			Opt:   opts,
		})

	elephantRPC, err := elephantRPCPlugin()
	if err != nil {
		return err
	}

	if elephantRPC != nil {
		tpl.Plugins = append(tpl.Plugins, bufPlugin{
			Local: elephantRPC,
			Out:   ".",
			Opt: append(append([]string{}, opts...),
				elephantRPCOptions(conf)...),
		})
	}

	if conf.Twirp {
		tpl.Plugins = append(tpl.Plugins, bufPlugin{
			Local: goRun(twirpModule, TwirpVersion),
			Out:   ".",
			Opt:   opts,
		})
	}

	data, err := json.Marshal(tpl)
	if err != nil {
		return fmt.Errorf("marshal the buf template: %w", err)
	}

	args := []string{"generate", "--template", string(data)}

	// Without --path buf would generate for every file in the workspace,
	// vendored imports included, and their Go code belongs to the module
	// they were vendored out of.
	for _, s := range services {
		args = append(args, "--path", s.Dir)
	}

	err = buf(args...)
	if err != nil {
		return fmt.Errorf("run buf generate: %w", err)
	}

	return nil
}

// buf runs the pinned protobuf compiler.
func buf(args ...string) error {
	full := append(goRun(bufModule, BufVersion), args...)

	err := sh.RunV(full[0], full[1:]...)
	if err != nil {
		return fmt.Errorf("run buf: %w", err)
	}

	return nil
}

// pluginOptions returns the options every plugin is given: source relative
// output, so that a file is generated next to the .proto it came from, and
// the Go import path of every proto file that does not declare a usable one
// itself.
func pluginOptions(services []service) ([]string, error) {
	opts := []string{"paths=source_relative"}

	mappings, err := goImportPathOverrides(services)
	if err != nil {
		return nil, err
	}

	opts = append(opts, mappings...)

	return opts, nil
}

var goPackageExp = regexp.MustCompile(
	`(?m)^\s*option\s+go_package\s*=\s*"([^"]+)"`)

// goImportPathOverrides returns an M<file>=<import path> option per proto
// file that declares a relative go_package, or none at all.
//
// protoc-gen-go only takes the last element of go_package, as the name of
// the package it writes, so "./rpc/collab" has always worked. Connect
// generates into a subdirectory and has to import the message package, which
// a relative path cannot be turned into. Rather than making every repository
// edit its .proto files, the import path is derived here from the module
// path and the file's directory, which is where source relative output puts
// the generated code anyway.
func goImportPathOverrides(services []service) ([]string, error) {
	var (
		module string
		opts   []string
	)

	for _, s := range services {
		files, err := protoFiles(s.Dir)
		if err != nil {
			return nil, err
		}

		for _, f := range files {
			declared, err := declaredGoPackage(f)
			if err != nil {
				return nil, err
			}

			if isImportPath(declared) {
				continue
			}

			if module == "" {
				module, err = modulePath()
				if err != nil {
					return nil, err
				}
			}

			opts = append(opts, fmt.Sprintf("M%s=%s/%s",
				filepath.ToSlash(f), module, s.Dir))
		}
	}

	sort.Strings(opts)

	return opts, nil
}

// isImportPath reports whether a go_package declaration can be used as the
// Go import path of the generated package.
func isImportPath(goPackage string) bool {
	// A ";name" suffix names the package separately from the path.
	path, _, _ := strings.Cut(goPackage, ";")

	if path == "" || strings.HasPrefix(path, ".") {
		return false
	}

	return strings.Contains(path, "/")
}

func declaredGoPackage(file string) (string, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return "", fmt.Errorf("read %q: %w", file, err)
	}

	match := goPackageExp.FindSubmatch(data)
	if match == nil {
		return "", nil
	}

	return string(match[1]), nil
}

func protoFiles(dir string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.proto"))
	if err != nil {
		return nil, fmt.Errorf("glob for proto files in %q: %w", dir, err)
	}

	return files, nil
}

func modulePath() (string, error) {
	path, err := internal.OutputSilent("go", "list", "-m", "-f", "{{.Path}}")
	if err != nil {
		return "", fmt.Errorf("resolve the Go module path: %w", err)
	}

	path = strings.TrimSpace(path)
	if path == "" {
		return "", fmt.Errorf(
			"the Go module path is empty, so the import path of the generated code cannot be derived")
	}

	return path, nil
}

// ensureBufConfig writes the buf workspace configuration, when the workspace
// needs one. A single module rooted in the repository is what buf assumes
// with no configuration at all, and that is the common case.
func ensureBufConfig(conf config) error {
	roots, err := workspaceRoots(conf)
	if err != nil {
		return err
	}

	if len(roots) == 0 {
		return nil
	}

	wanted := bufConfig(roots)

	current, err := os.ReadFile(bufConfigName)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", bufConfigName, err)
	}

	if len(current) > 0 && !strings.HasPrefix(string(current), bufConfigMarker) {
		// Somebody wrote their own workspace configuration. Buf lint and
		// breaking change rules live in the same file, so overwriting it
		// would throw those away.
		return nil
	}

	if string(current) == wanted {
		return nil
	}

	err = os.WriteFile(bufConfigName, []byte(wanted), 0o600)
	if err != nil {
		return fmt.Errorf("write %s: %w", bufConfigName, err)
	}

	return nil
}

// workspaceRoots returns the proto roots beyond the repository root, or
// nothing when there are none.
func workspaceRoots(conf config) ([]string, error) {
	var roots []string

	vendored, err := internal.DirectoryExists(conf.VendorDir)
	if err != nil {
		return nil, fmt.Errorf("check for the vendored proto root: %w", err)
	}

	if vendored {
		roots = append(roots, conf.VendorDir)
	}

	for _, r := range conf.ExtraProtoRoots {
		roots = append(roots, filepath.ToSlash(r))
	}

	return roots, nil
}

func bufConfig(roots []string) string {
	var b strings.Builder

	b.WriteString(bufConfigMarker)
	b.WriteString(`
#
# A vendored protobuf file is imported by the path it has in the repository
# it came from, so its directory has to be a module root of its own, and be
# excluded from the module rooted here.
version: v2
modules:
  - path: .
    excludes:
`)

	for _, r := range roots {
		fmt.Fprintf(&b, "      - %s\n", r)
	}

	for _, r := range roots {
		fmt.Fprintf(&b, "  - path: %s\n", r)
	}

	return b.String()
}
