// Command protoc-gen-elephant-rpc stands in for the real plugin in the tests
// of the rpc package, which has to be able to run a plugin that has no
// released version yet. It emits one file per proto file that declares a
// service, into the package protoc-gen-connect-go generates into.
package main

import (
	"fmt"
	"io"
	"os"
	"path"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	err := run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "protoc-gen-elephant-rpc: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	input, err := io.ReadAll(os.Stdin)
	if err != nil {
		return fmt.Errorf("read the request: %w", err)
	}

	var req pluginpb.CodeGeneratorRequest

	err = proto.Unmarshal(input, &req)
	if err != nil {
		return fmt.Errorf("unmarshal the request: %w", err)
	}

	generate := make(map[string]bool, len(req.GetFileToGenerate()))

	for _, name := range req.GetFileToGenerate() {
		generate[name] = true
	}

	var resp pluginpb.CodeGeneratorResponse

	for _, file := range req.GetProtoFile() {
		if !generate[file.GetName()] || len(file.GetService()) == 0 {
			continue
		}

		dir := path.Dir(file.GetName())
		pkg := path.Base(dir) + "connect"
		name := path.Join(dir, pkg,
			stripExtension(path.Base(file.GetName()))+".elephant.go")

		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name: proto.String(name),
			Content: proto.String(fmt.Sprintf(
				"// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.\n\n"+
					"package %s\n\n"+
					"// Source is the file this was generated from.\n"+
					"const Source = %q\n",
				pkg, file.GetName())),
		})
	}

	output, err := proto.Marshal(&resp)
	if err != nil {
		return fmt.Errorf("marshal the response: %w", err)
	}

	_, err = os.Stdout.Write(output)
	if err != nil {
		return fmt.Errorf("write the response: %w", err)
	}

	return nil
}

func stripExtension(name string) string {
	return name[:len(name)-len(path.Ext(name))]
}
